// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using MTG_CARDSHOP_ADMIN;
//
//    var cutomer = Cutomer.FromJson(jsonString);

namespace MTG_CARDSHOP_ADMIN
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Customer
    {
        [JsonProperty("customer_id")]
        public long CustomerId { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("phone_number")]
        public string PhoneNumber { get; set; }

        [JsonProperty("registration_date")]
        public DateTimeOffset RegistrationDate { get; set; }
    }

    public partial class Customer
    {
        public static List<Customer> FromJson(string json) => JsonConvert.DeserializeObject<List<Customer>>(json, MTG_CARDSHOP_ADMIN.CustomersConverter.Settings);
    }

    public static class CustomersSerialize
    {
        public static string ToJson(this List<Customer> self) => JsonConvert.SerializeObject(self, MTG_CARDSHOP_ADMIN.CustomersConverter.Settings);
    }

    internal static class CustomersConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
